#! /bin/bash

DIR=$(cd $(dirname "$0"); pwd)
HOSTNAME=`hostname -s`
# generate the beamline name from the folder we are in
# (assumes this file is in etc. and  2 dirs above etc folder is the Beamline folder)
BEAMLINE=$(basename $(cd $DIR/../..; pwd))
WS=~/workspaces/cs-studio-$HOSTNAME-$BEAMLINE

killall -9 cs-studio
killall -9 /usr/bin/java


if [ "$1" ==  "-r" ]
then
    # remove previous
    echo "removing workspace $WS"
    rm -fr $WS
fi
