#!/bin/bash

# tar up the current workspace 

DIR=$(cd $(dirname "$0"); pwd) 
HOSTNAME=`hostname -s`
WS=~/workspaces/cs-studio-$HOSTNAME
TAR=$DIR/workspaceStartup.tar

echo "saving the workspace at $WS to $TAR"

rm $DIR/workspaceStartup.tar
cd $WS
tar -cf $DIR/workspaceStartup.tar * .metadata




