#!/bin/bash

# Run CSS up in a unique workspace 
#
# the first parameter is -r then remove workspace completely

DIR=$(cd $(dirname "$0"); pwd)
HOSTNAME=`hostname -s`
WS=~/workspaces/cs-studio/$HOSTNAME

if [ "$1" ==  "-r" ]
then
    # remove previous
    echo "removing previous workspace $WS"
    rm -fr $WS
    shift
fi

$DIR/../bin/linux-x86_64/launch_gui $@


