#!/usr/bin/env bash

function taskpart()
{
    echo "⚒ $(task-next-name.py)"
}

function datepart()
{
    local hour=$(date +%I)
    hour="${hour#0}"
    let hour=hour-1
    local syms="🕐🕑🕒🕓🕔🕕🕖🕗🕘🕙🕚🕛"
    echo "${syms:$hour:1} $(date '+%Y %b %d (%a) %H:%M')"
}

function batterypart()
{
    local level="$(cat /sys/class/power_supply/BAT1/capacity)"
    if [ $level -le 9 ]; then
        local index=0;
    elif [ $level -eq 100 ]; then
        local index=10
    else
        local index="${level:0:1}"
    fi
    local syms="▁▁▂▂▃▃▄▅▆▇█"
    echo "${syms:$index:1} ${level}%"
}

while true; do
    xsetroot -name "$(taskpart) $(datepart) $(batterypart)" | tr '\n' ' '
    sleep 1m
done

