#!/usr/bin/env bash

function taskpart()
{
    echo "⚒ $(task-next-name.py)"
}

function datepart()
{
    local hour=$(date +%I)
    hour="${hour#0}"
    let hour=hour-1
    local syms="🕐🕑🕒🕓🕔🕕🕖🕗🕘🕙🕚🕛"
    echo "${syms:$hour:1} $(date '+%Y %b %d (%a) %H:%M')"
}

function batterypart()
{
    for bat in /sys/class/power_supply/BAT*/capacity;
    do
        local level="$(cat $bat)"
        if [ $level -le 9 ]; then
            local index=0;
        elif [ $level -eq 100 ]; then
            local index=9
        else
            local index="${level:0:1}"
        fi
        local syms="▁▁▂▂▃▄▅▆▇█"
        echo "${syms:$index:1} ${level}%"
    done
}

while true; do
    xsetroot -name "$(taskpart) $(datepart)" | tr '\n' ' '
    sleep 1m
done

