#!/usr/bin/env bash

function taskpart()
{
    echo "⚒ $(task-next-name.py)"
}

function datepart()
{
    local hour=$(date +%I)
    let hour=hour-1
    local syms="🕐🕑🕒🕒🕒🕕🕖🕗🕘🕙🕙🕛"
    echo "${syms:$hour:1} $(date '+%Y %b %d (%a) %H:%M')"
}

while true; do
    xsetroot -name "$(taskpart) $(datepart)" | tr '\n' ' '
    sleep 1m
done

