# Don't print a new line at the start of the prompt
add_newline = false

[character]
# Keep it simple
symbol = "❯"

[directory]
truncation_length = 5
prefix = ""

[cmd_duration]
min_time = 3

[battery]
disabled = true

[golang]
disabled = true

[hostname]
# Hide hostname unless accessing via SSH
ssh_only = true

[jobs]
disabled = true

[nix_shell]
disabled = false

[package]
disabled = true

[python]
disabled = true

[java]
disabled = true

[ruby]
disabled = true

[rust]
disabled = true
