# Don't print a new line at the start of the prompt
add_newline = false
format = """
$username\
$hostname\
$directory\
$git_branch\
$git_commit\
$git_state\
$nix_shell\
$env_var\
$cmd_duration\
$custom\
$time\
$line_break\
$jobs\
$status\
$character"""

[cmd_duration]
min_time = 3

[directory]
truncation_length = 5
format = "[$path]($style) [$read_only]($read_only_style) "

[env_var.nr_open]
format = " in virtme-ng ($style) "
variable = 'nr_open'

[hostname]
# Hide hostname unless accessing via SSH
ssh_only = true

[status]
disabled = false

