#!/usr/bin/env bash
# Fix java applications
export _JAVA_AWT_WM_NONREPARENTING=1

for monitor in $(xrandr -q | grep -w 'connected' | cut -d' ' -f1); do
    bspc monitor "$monitor" -d 1 2 3 4 5
    MONITOR=$monitor polybar -r main &
done

bspc config border_width              1
bspc config window_gap                2

bspc config split_ratio               0.52
bspc config single_monocle            true
bspc config borderless_monocle        true

bspc config focus_follows_pointer     true

# Rules
bspc rule -a scratch state=floating
bspc rule -a edm state=floating
bspc rule -a cs-studio state=floating
bspc rule -a Conky state=floating
bspc rule -a zoom state=floating

# set wallpaper and colors
wal -q -R
. "~/.cache/wal/colors.sh"
bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"
bspc config presel_feedback_color "$color1"

sxhkd &
watchudev.py &
xsetroot -cursor_name left_ptr
