#!/usr/bin/env python
from __future__ import print_function
import shlex
import sys


for line in sys.stdin:
    try:
        print("\n".join(shlex.split(line)))
    except Exception:
        print("\n".join(line.split()))
