#!/usr/bin/env bash

function datepart()
{
    echo "$(date '+%Y %b %d (%a) %H:%M')"
}

function batterypart()
{
    for bat in /sys/class/power_supply/BAT*/capacity;
    do
        local level="$(cat $bat)"
        if [ $level -le 9 ]; then
            local index=0;
        elif [ $level -eq 100 ]; then
            local index=9
        else
            local index="${level:0:1}"
        fi
        local syms="▁▁▂▂▃▄▅▆▇█"
        echo "${syms:$index:1} ${level}%"
    done
}

while true; do
    xsetroot -name "$(datepart) $(batterypart)" | tr '\n' ' '
    sleep 1m
done
